# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/moz',
                'doc_host': 'https://miklevin.github.io',
                'git_url': 'https://github.com/miklevin/moz',
                'lib_path': 'moz'},
  'syms': { 'moz.auto_keywords': { 'moz.auto_keywords.in_notebook': ('chrome_automation.html#in_notebook', 'moz/auto_keywords.py'),
                                   'moz.auto_keywords.main': ('chrome_automation.html#main', 'moz/auto_keywords.py'),
                                   'moz.auto_keywords.run_main': ('chrome_automation.html#run_main', 'moz/auto_keywords.py')},
            'moz.core': {'moz.core.foo': ('core.html#foo', 'moz/core.py')},
            'moz.data': { 'moz.data.fig': ('data.html#fig', 'moz/data.py'),
                          'moz.data.get_domain': ('data.html#get_domain', 'moz/data.py'),
                          'moz.data.get_url': ('data.html#get_url', 'moz/data.py')}}}
