# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/moz',
                'doc_host': 'https://miklevin.github.io',
                'git_url': 'https://github.com/miklevin/moz',
                'lib_path': 'moz'},
  'syms': { 'moz.core': {'moz.core.foo': ('core.html#foo', 'moz/core.py')},
            'moz.mozpro': { 'moz.mozpro.in_notebook': ('chrome_automation.html#in_notebook', 'moz/mozpro.py'),
                            'moz.mozpro.main': ('chrome_automation.html#main', 'moz/mozpro.py'),
                            'moz.mozpro.run_main': ('chrome_automation.html#run_main', 'moz/mozpro.py')}}}
